{
  imports = [
    ./yazi/default.nix
    ./atuin/default.nix
    ./bat/default.nix
    ./carapace/default.nix
    ./clock-rs/default.nix
    ./eza/default.nix
    ./fastfetch/default.nix
    ./fd/default.nix
    ./fzf/default.nix
    ./git/default.nix
    ./lazygit/default.nix
    ./neovim/default.nix
    ./pay-respects/default.nix
    ./ripgrep/default.nix
    ./zoxide/default.nix
    ./navi/default.nix
    ./tealdeer/default.nix
    ./nh/default.nix
    ./jujutsu/default.nix
    ./btop/default.nix
    ./helix/default.nix
    ./navi/default.nix
  ];
}
