name: Dead code analysis

on:
  workflow_dispatch:
  push:

jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: phucleeuwu/deadnix-action@main
