name: Statix Linter

on:
  workflow_dispatch:
  push:

jobs:
  statix:
    name: Statix Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: phucleeuwu/statix-action@main
